server:
  port: 8769
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      max: 800
      min-spare: 30
  # 优雅停机，默认是IMMEDIATE立即停机
  shutdown: graceful
spring:
  security:
    user:
      name: admin
      password: admin#8769
  application:
    name: @project.name@
    admin:
      enabled: true
  devtools:
    add-properties: true
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    org.springframework: warn

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://192.168.163.1:8761}/eureka/
    eureka-server-connect-timeout-seconds: 30
    eureka-server-read-timeout-seconds: 30
    eureka-connection-idle-timeout-seconds: 60
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    spring-boot-version: @project.parent.version@
