server:
  port: 8878
  shutdown: graceful
spring:
  application:
    # 注册到nacos上的服务名称
    name: @project.name@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#logging:
#  level:
#    org.springframework: info
