spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://192.168.137.67:8769/
        username: admin
        password: admin#8769
server:
  port: 8768

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://192.168.137.67:8761}/eureka/
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    spring-boot-version: @project.parent.version@
